SET (TEST_SOURCES
    ${CALLGRAPH_TEST_SRC}/teststacklog.cpp
)

SET (TEST_HEADERS
    ${HEADERS}
)

ADD_HATN_CTESTS(callgraph ${TEST_SOURCES} ${TEST_HEADERS})

FUNCTION(TestCallgraph)
    COPY_LIBRARY_HERE(hatncommon${LIB_POSTFIX} ../common/)
    COPY_LIBRARY_HERE(hatncallgraph${LIB_POSTFIX} ../callgraph/)
ENDFUNCTION(TestBase)

ADD_CUSTOM_TARGET(callgraphtest-src SOURCES ${TEST_HEADERS} ${TEST_SOURCES} ${SOURCES})
