INSTALL(DIRECTORY "${HATN_SOURCE_DIR}/cmake" DESTINATION lib)
INSTALL(DIRECTORY "${HATN_SOURCE_DIR}/scripts" DESTINATION lib/hatn
    PATTERN "__pycache__" EXCLUDE
    PATTERN "*.pyc" EXCLUDE
)
INSTALL(FILES ${HATN_SOURCE_DIR}/VERSION
    DESTINATION lib/cmake/hatn
)
